/* ISHAARA — generated by tools/wire-v2.js. Do not edit.
   Build 20260812150310.

   Why a worker at all: the consent screen promises the app keeps working
   without a connection, and until now that was untrue — the page is one file,
   but MediaPipe's wasm and model come from two CDNs on every visit, so a
   reload on a bad connection was a blank screen.

   Three rules, in order:
     · GitHub is never cached. "Check for updates" has to be able to tell you
       something you do not already know.
     · The CDN assets are content-addressed and immutable, so cache-first.
     · The page itself is network-first, so a rebuild is picked up on the next
       load rather than being pinned by a cache nobody can clear. */
const CACHE = 'ishaara-20260812150310';
const CDN = [/^https:\/\/cdn\.jsdelivr\.net\//, /^https:\/\/storage\.googleapis\.com\//];
const NEVER = [/^https:\/\/raw\.githubusercontent\.com\//, /^https:\/\/api\.github\.com\//];

self.addEventListener('install', e => self.skipWaiting());

self.addEventListener('activate', e => e.waitUntil((async () => {
  /* one cache per build; the rest go */
  const keys = await caches.keys();
  await Promise.all(keys.filter(k => k.startsWith('ishaara-') && k !== CACHE).map(k => caches.delete(k)));
  await self.clients.claim();
})()));

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;
  if (NEVER.some(re => re.test(url))) return;            /* straight to network */

  if (CDN.some(re => re.test(url))) {
    e.respondWith((async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      /* opaque responses are cached too: they are useless to read but they
         still replay offline, which is the whole point */
      if (res && (res.ok || res.type === 'opaque')) {
        const c = await caches.open(CACHE); c.put(req, res.clone());
      }
      return res;
    })());
    return;
  }

  if (req.mode === 'navigate' || (req.destination === 'document')) {
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res && res.ok) { const c = await caches.open(CACHE); c.put(req, res.clone()); }
        return res;
      } catch (err) {
        const hit = await caches.match(req);
        if (hit) return hit;
        throw err;
      }
    })());
  }
});
